language: c

arch:
  - arm64

os: linux

cache:
  directories:
    - bin/linux/arm/java
    - bin/scala

script:
  - if echo "$TRAVIS_COMMIT_MESSAGE" | grep -F -q "[skip travis]" ; then echo "skip travis" && exit 0 ; fi
  - unset JVM_OPTS
  - bin/build.cmd test