name: CI

on: [push]

jobs:

  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2-beta
      - name: Set env.workspace
        run: echo "::set-env name=workspace::$GITHUB_WORKSPACE"
      - name: Test
        run: |
          export COURSIER_CACHE=$GITHUB_WORKSPACE/cache/coursier
          cd $GITHUB_WORKSPACE
          git submodule update --init --recursive
          bin/build.cmd test

  build-mac:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2-beta
      - name: Set env.workspace
        run: echo "::set-env name=workspace::$GITHUB_WORKSPACE"
      - name: Test
        run: |
          export COURSIER_CACHE=$GITHUB_WORKSPACE/cache/coursier
          cd $GITHUB_WORKSPACE
          git submodule update --init --recursive
          bin/build.cmd test

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2-beta
      - name: Set env.workspace
        run: echo "::set-env name=workspace::$($env:GITHUB_WORKSPACE)"
      - name: Install Cygwin
        shell: cmd
        run: |
          choco config get cacheLocation
          choco install --no-progress cygwin
          C:\tools\cygwin\cygwinsetup.exe -qgnNdO -R C:/tools/cygwin -s http://mirrors.kernel.org/sourceware/cygwin/ -P gcc-core,make,cmake
      - name: Test
        shell: cmd
        run: |
          set COURSIER_CACHE=%GITHUB_WORKSPACE%\cache\coursier
          set PATH=%PATH%;C:\tools\cygwin\bin;C:\tools\cygwin\usr\bin
          cd /d %GITHUB_WORKSPACE%
          git submodule update --init --recursive
          bin\build.cmd test